language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t blakehowe/docker-react -f Dockerfile.dev .

script:
  - docker run blakehowe/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-918450492472"
  bucket_path: "docker-react"
  on:
    branch: master